version: '3'
services:
  dev:
    container_name: docker-angular-base
    build: .
    image: pajarraco/docker-angular-base
    volumes:
      - ./src:/app/src
    ports:
      - "4200:4200"
  
  deploy:
    build: 
      context: .
      dockerfile: Dockerfile-build
    volumes:
      - ./dist:/app/build
    