version: '3'
services:
  dev:
    container_name: docker-angular-base
    build: .
    image: pajarraco/docker-angular-base
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
      - "9229:9229"
    expose:
      - "9229"
    command: node --inspect=0.0.0.0:9229 index.js

  deploy:
    build:
      context: .
      dockerfile: Dockerfile-build
    volumes:
      - ./dist:/app/build
