version: '3'
services:
  docker-angular-base:
    container_name: docker-angular-base
    build: .
    image: pajarraco/docker-angular-base:node8
    volumes:
      - ./src:/app/src
      - ./dist:/app/build
    ports:
      - "4200:4200"
    command: npm run build