version: "3"
services:
  deploy:
    container_name: docker-angular-base
    build: .
    image: pajarraco/docker-angular-base
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
      - "9229:9229"
    expose:
      - "9229"
    command: node --inspect=0.0.0.0:9229 index.js

  dev:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
    ports:
      - "4200:4200"